[bench]
name        = 'GSC_ResNetv1-8_no_fused_bias_wise_near_ICONIP_livemfcc_QAT4_6_8_train'
seed        = 2
first_run   = 1
last_run    = 3

[learningframework]
kind  = 'PyTorch'
params.devices  = [0]

#[experimenttracking]
#kind = "ClearML"
#params.project_name = "GSC_ICONIP"
#params.task_name = 'GSC_ResNetv1-8_no_fused_ICONIP_livemfcc_QAT4_and_8_train'

[deploy]
target          = 'Linux'
converter.kind  = 'QualiaCodeGen'
quantize        = ['float32']
optimize        = ['']
compress        = [1]

[dataset]
kind            = 'GSC'
params.variant  = 'v2'
params.path     = "/home/jupyter-tlouis/shared/speech_commands_v0.02/"
params.subset   = 'no_background_noise'

[[preprocessing]]
kind            = 'Class2BinMatrix'

[[preprocessing]]
kind            = 'Normalize'
params.method   = 'z-score'
params.axis     = 0
params.debug    = true

[[data_augmentation]]
kind            = 'GaussianNoise'
params.sigma    = 0.00175

[[data_augmentation]]
kind            = 'TimeWarping'
params.sigma    = 0.0675

[[data_augmentation]]
kind            = 'TimeShifting'
params.alpha    = 1.0

[[data_augmentation]]
kind                            = 'MFCC'
params.evaluate                 = true
params.sample_rate              = 16000
#params.n_mfcc                   = 64
params.n_mfcc                   = 10
params.log_mels                 = true
params.melkwargs.n_fft          = 1024
params.melkwargs.n_mels         = 40
#params.melkwargs.win_length     = 1024
params.melkwargs.win_length     = 640
#params.melkwargs.hop_length     = 128
fparams.melkwargs.hop_length    = 320
params.melkwargs.f_min          = 20
params.melkwargs.f_max          = 4000
params.melkwargs.pad            = 320
params.melkwargs.center         = false

[[postprocessing]]
kind                = "QuantizationAwareTraining"
export              = true
params.epochs       = 100
params.batch_size   = 800
params.model.params.quantize_linear             = true
params.model.params.quant_params.bits           = 4
params.model.params.quant_params.quantype       = "fxp"
params.model.params.quant_params.roundtype      = "nearest"
params.model.params.quant_params.range_setting  = "minmax"
params.model.params.quant_params.input.quant_enable=false
params.model.params.quant_params.LSQ            = false
params.model.params.quant_params.bias.quant_enable=true

[model_template]
kind                = 'ResNet'
epochs              = 100
batch_size          = 800
load                = true
train               = false
params.input_shape  = [49, 10]
params.batch_norm   = true
params.bn_momentum  = 0.1
params.dims         = 1
params.prepool      = 1


[model_template.optimizer]
kind                = "Adam"
params.lr           = 0.01
#params.momentum	= 0.9
params.weight_decay = 5e-4

[model_template.optimizer.scheduler]
kind                = "MultiStepLR"
params.milestones	= [25, 55, 80, 95, 110, 115]
params.gamma		= 0.25


# With no Fuse - Q4

[[model]]
name                        = 'GSC_ResNet-8_ICONIP_float'
params.filters              = [64, 64]
params.kernel_sizes         = [7, 3]
params.paddings             = [3, 1]
params.strides              = [1, 1]
params.num_blocks           = [3]
params.batch_norm           = true
update.quant_params.bits    = 4
disabled                    = false

# With no Fuse - Q6

[[model]]
name                        = 'GSC_ResNet-8_ICONIP_float'
params.filters              = [64, 64]
params.kernel_sizes         = [7, 3]
params.paddings             = [3, 1]
params.strides              = [1, 1]
params.num_blocks           = [3]
params.batch_norm           = true
update.quant_params.bits    = 6
disabled                    = false

# With no Fuse - Q8

[[model]]
name                        = 'GSC_ResNet-8_ICONIP_float'
params.filters              = [64, 64]
params.kernel_sizes         = [7, 3]
params.paddings             = [3, 1]
params.strides              = [1, 1]
params.num_blocks           = [3]
params.batch_norm           = true
update.quant_params.bits    = 8
disabled                    = false
