variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  image: archlinux:latest
  before_script:
    - pacman -Syu --noconfirm --needed git which curl wget unzip make gcc arm-none-eabi-gcc arm-none-eabi-newlib vim
    - pacman -S --noconfirm --needed python-pytorch python-pip python-numpy # python-tensorflow 
    - pacman -S --noconfirm --needed python-scikit-learn python-pycryptodome python-pyserial python-tomlkit python-gitpython
    - pacman -S --noconfirm --needed python-tabulate python-matplotlib python-pydot
    - pacman -S --noconfirm --needed python-pytest python-pytest-dependency python-pytest-xdist python-pytest-env
    - pacman -S --noconfirm --needed python-torchvision python-jinja python-tqdm python-networkx python-aiohttp
    - pacman -S --noconfirm --needed python-async-timeout python-charset-normalizer python-frozenlist python-multidict 
    - pacman -S --noconfirm --needed python-yarl python-aiosignal python-dill python-filelock
    - pacman -S --noconfirm --needed python-blosc2 python-fsspec python-typing_extensions python-pydantic
    - pacman -S --noconfirm --needed cmake ninja
    - pacman -U --noconfirm /mnt/hdd/Software/STMicroelectronics/STM32CubeIDE/stm32cubeide-1.12.0-2-x86_64.pkg.tar.zst
    - pacman -U --noconfirm /mnt/hdd/Software/Ambiq/ambiqsuite-2.5.1-2-any.pkg.tar.zst
    - mkdir -p ~/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/5.2.0/Utilities
    - unzip /mnt/hdd/Software/STMicroelectronics/X-CUBE-AI/en.x-cube-ai-v5-2-0-linux.zip
    - unzip -q stm32ai-linux-5.2.0.zip -d ~/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/5.2.0/Utilities

stages:          # List of stages for jobs, and their order of execution
  - test
  - deploy
  - doc

test-job:       # This job runs in the build stage, which runs first.
  stage: test
  script:
    - mkdir data
    - pushd data
    - tar -xf "/mnt/hdd/Datasets/cifar-10-python.tar.gz"
    - unzip -q "/mnt/hdd/Datasets/UCI%20HAR%20Dataset.zip"
    - ln -s /mnt/hdd/Datasets/WSMNIST ./
    - unzip -q /mnt/hdd/Datasets/GTSRB/GTSRB_Final_Training_Images.zip
    - unzip -q /mnt/hdd/Datasets/GTSRB/GTSRB_Final_Test_Images.zip
    - pushd GTSRB
    - unzip -q /mnt/hdd/Datasets/GTSRB/GTSRB_Final_Test_GT.zip
    - popd
    - popd
    - tar -C third_party/tflite-micro/tensorflow/lite/micro/tools/make -xf /mnt/hdd/Software/TensorFlow/tflite-micro/downloads.tar.zst
    - pip install --break-system-packages -e .[tests,pytorch,tensorflow,gtsrb,codegen] --extra-index-url=https://naixtech.unice.fr/devpi/penovac/qualia-nightly/+simple --trusted-host naixtech.unice.fr
    - pytest -m "not deploy" -n auto --dist=loadgroup -vvv -s # xdist incompatible with dependency

deploy-job:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - pacman -Syu --noconfirm --needed python-build python-pkginfo python-py python-lazy python-pyproject-hooks python-packaging
    - pacman -S --noconfirm --needed python-setuptools python-pyparsing python-pluggy python-platformdirs python-requests
    - pacman -S --noconfirm --needed python-pip git
    - pip install --break-system-packages devpi-client git+http://naixtech.unice.fr/gitlab/penovac/devpi-client-password-stdin.git
  script:
    - devpi use http://naixtech.unice.fr/devpi
    - devpi login gitlab < ${GITLAB_LDAP_PASSWORD}
    - devpi use penovac/qualia-nightly
    - devpi upload

doc-job:
  stage: doc
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - pacman -Syu --noconfirm --needed rclone make git
    - pacman -S --noconfirm --needed python-sphinx python-sphinx-autodoc-typehints python-sphinx_rtd_theme python-myst-parser
    - pacman -S --noconfirm --needed python-pip python-pdm python-numpy python-pytorch python-keras
    - pacman -S --noconfirm --needed python-docutils python-torchvision python-tqdm
    - pacman -S --noconfirm --needed python-blosc2 python-gitpython python-pycryptodome python-pyserial python-scikit-learn
    - pacman -S --noconfirm --needed python-tabulate python-fsspec python-aiohttp
  script:
    - pip install --break-system-packages -e .[pytorch,docs] --extra-index-url=https://naixtech.unice.fr/devpi/penovac/qualia-nightly/+simple --trusted-host naixtech.unice.fr
    - make -C docs html
    - read RCLONE_SFTP_PASS < <(rclone obscure - < ${GITLAB_LDAP_PASSWORD}) && export RCLONE_SFTP_PASS
    - rclone sync --sftp-host naixtech.unice.fr --sftp-user gitlab docs/_build/html :sftp:/gitlab/public_html/docs/qualia-core
