[bench]
name = "BrainMIX_float32_train"
seed = 2
first_run = 1
last_run = 1
use_test_as_valid = true

[learningframework]
kind = 'PyTorch'
params.loss = 'mse'
params.metrics = ['mse', 'mae', 'corr']
params.enable_confusion_matrix = false
params.checkpoint_metric.name = 'trainmse'
params.checkpoint_metric.mode = 'min'

[experimenttracking]
kind = "ClearML"
params.project_name = "BrainMIX"
params.task_name = "BrainMIX_float32_train"

[deploy]
#target = 'SparkFunEdge'
target  = 'Linux'
#deployer.params.dev = '/dev/serial/by-id/usb-1a86_USB2.0-Serial-*'
#evaluator.params.dev = '/dev/serial/by-id/usb-1a86_USB2.0-Serial-*'
converter.kind = 'QualiaCodeGen'
converter.params.metrics = ['mse', 'corr']
evaluator.params.chunks = 1
quantize = ['float32']
optimize = ['']
#limit = 50

[dataset]
kind = "BrainMIX"
params.path = "data/BrainMIX"

[[data_augmentation]]
kind = "GaussianNoise"
params.sigma = 0.125

#[[data_augmentation]]
#kind = "Amplitude"
#params.sigma = 4
#params.distribution = 'normal'
#params.distribution = 'uniform'
#params.low = 0.125
#params.high = 16
#params.low = 1.0
#params.high = 16.0
#params.evaluate = true

[[postprocessing]]
kind = "FuseBatchNorm"
export = true

[model_template]
#epochs = 80
epochs = 8
batch_size = 1024

[model_template.optimizer]
#kind = "RMSprop"
kind = "RAdam"
params.lr = 0.01
params.weight_decay = 5e-4

[model_template.optimizer.scheduler]
kind = "StepLR"
params.step_size = 20
params.gamma = 0.2

[[model]]
kind = "CNN"
name = "brainmix_cnn_s20230616_m3"
params.filters = [16, 32, 64, 64]
params.kernel_sizes = [3, 3, 3, 3]
params.strides = [1, 1, 1, 1]
params.paddings = [0, 0, 0, 0]
params.pool_sizes = [2, 2, 2, 2]
params.dropouts = [0, 0, 0, 0, 0, 0]
params.batch_norm = true
params.fc_units = [16]
disabled = false

# DA: amplitude=off, gaussiannoise sigma=0.125
# Train
#│         testcorr          │     0.886674165725708     │
#│          testmae          │    0.05987832695245743    │
#│          testmse          │    0.00677597476169467
# Test
#│         testcorr          │    0.8866742253303528     │
#│          testmae          │    0.05987832322716713    │
#│          testmse          │   0.006775971502065659    │
[[model]]
kind = "ResNet"
name = "brainmix_resnet_s20230616_m3"
params.filters      = [4, 4, 8, 16, 32, 64]
params.kernel_sizes = [3, 3, 3, 3, 3, 3]
params.paddings     = [1, 1, 1, 1, 1, 1]
params.strides      = [1, 2, 2, 2, 2, 2]
params.num_blocks   = [1, 1, 1, 1, 1]
params.batch_norm   = true
disabled = true

[[model]]
kind = "ResNet"
name = "brainmix_resnet_large_s20230616_m3"
params.filters      = [8, 8, 16, 32, 64, 128]
params.kernel_sizes = [3, 3, 3, 3, 3, 3]
params.paddings     = [1, 1, 1, 1, 1, 1]
params.strides      = [1, 2, 2, 2, 2, 2]
params.num_blocks   = [1, 2, 2, 2, 2]
params.batch_norm   = true
disabled = true
