[bench]
name = "Ellcie-HAR_PACK-2-3_ResNetv1_float32_train"
seed = 4
first_run = 1
last_run = 15

[learningframework]
kind = 'pytorch'

[deploy]
target = 'Linux'
converter.kind = 'QualiaCodeGen'
quantize = ['float32']
optimize = ['']
compress = [1]

[dataset]
kind = "EllcieHAR"
params.variant = "PACK-2"
params.path = "/home/piernov/Documents/data/EllcieHAR/PACK-2+3+4"

#[[preprocessing]]
#kind = "RemoveActivity"
#params.activities = [
	#"STANDING",
	#"STAND_TO_SIT",
	#"SITTING",
	#"SIT_TO_STAND",
	#"WALKING",
	#"LYING",
	#"WALKING_DOWNSTAIRS",
	#"WALKING_UPSTAIRS",
	#"DRIVING",
	#"NODDING",
	#"TRANSITION",
	#"RUNNING",
	#"DRINKING",
	#"SIT_TO_LIE",
	#"LIE_TO_SIT"
#]

[[preprocessing]]
kind = "RemoveSensor"
params.sensorkinds = ["Barometer"]

#[[preprocessing]]
#kind = "BandPassFilter"
#params.f1 = 0.01
#params.f2 = 1.0
##params.f2 = 100.0
#params.sensorkind = "Barometer"
#params.dimension = "p"

[[preprocessing]]
kind = "DatasetSplitterBySubjects"
#['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = []

params.source_subjects = ['T3', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
params.dest_subjects = ['T1', 'T2', 'T4']

#params.source_subjects = ['T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T1', 'T2', 'T3', 'T4']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T5', 'T6', 'T7', 'T8']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T9', 'T10', 'T12', 'T13']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T14', 'T16', 'T17', 'T18']
#params.source_subjects = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18']
#params.dest_subjects = ['T19', 'T20', 'T21', 'T1']
params.source = "train"
params.dest = "test"

[[preprocessing]]
kind = "DatamodelConverter"

[[preprocessing]] # Must be applied before Class2BinMatrix and DatasetSplitter
kind = "Window"
params.size = 64
params.stride = 32

[[preprocessing]] # Must be applied after Window
kind = "Class2BinMatrix"
params.classes = 13 # PACK-2 12 classes, T1 15 classes, PACK-2+3 13 classes

#[[preprocessing]]
#kind = "Normalize"
#params.method = 'z-score'
#params.axis = 0
#params.debug = true

[[data_augmentation]]
kind = "Mixup"

[[data_augmentation]]
kind = "TimeShifting"

[[data_augmentation]]
kind = "Rotation"

[[postprocessing]]
kind = "Torch2Keras"
params.mapping = 'conf/torch2keras/resnetv1-6.toml'

[[postprocessing]]
kind = "RemoveKerasSoftmax"
export = true

[model_template]
kind = "ResNet"
epochs = 120
batch_size = 128
params.prepool 		= 1
params.strides		= [1, 2]
params.num_blocks	= [2]
#load = true
#train = false

[model_template.optimizer]
kind = "SGD"
params.lr               = 0.05
params.momentum		= 0.9
params.weight_decay	= 5e-4

[model_template.optimizer.scheduler]
kind = "MultiStepLR"
params.milestones	= [60, 90, 105]
params.gamma		= 0.1

[[model]]
name = "ellciehar_resnetv1_8"
params.filters 		= [8, 8]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false

[[model]]
name = "ellciehar_resnetv1_16"
params.filters 		= [16, 16]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false

[[model]]
name = "ellciehar_resnetv1_24"
params.filters 		= [24, 24]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false

[[model]]
name = "ellciehar_resnetv1_32"
params.filters 		= [32, 32]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false

[[model]]
name = "ellciehar_resnetv1_40"
params.filters 		= [40, 40]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false

[[model]]
name = "ellciehar_resnetv1_48"
params.filters 		= [48, 48]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false

[[model]]
name = "ellciehar_resnetv1_64"
params.filters 		= [64, 64]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false

[[model]]
name = "ellciehar_resnetv1_80"
params.filters 		= [80, 80]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = false
