identity1 = 'input_1'
conv1 = 'conv1d'
layers.0.0.conv1 = 'conv1d_1'
layers.0.0.pool1 = 'max_pooling1d'
layers.0.0.conv2 = 'conv_ref'
layers.0.0.sconv = 'conv_shortcut'
layers.0.0.smax = 'max_pooling1d_1'
layers.0.0.add = 'tf.__operators__.add'
layers.0.1.conv1 = 'conv1d_2'
layers.0.1.conv2 = 'conv_ref_1'
layers.0.1.add = 'tf.__operators__.add_1'
postpool = 'max_pooling1d_4'
flatten = 'flatten'
linear = 'dense'
