[bench]
name = "UCI-HAR_ResNetv1_QualiaCodeGen_SparkFunEdge_int8_evaluate"
seed = 2
first_run = 1
last_run = 15

[learningframework]
kind = 'PyTorch'

[deploy]
target = 'SparkFunEdge'
deployer.params.dev = '/dev/ttyUSB0'
evaluator.params.dev = '/dev/ttyUSB0'
converter.kind = 'QualiaCodeGen'
quantize = ['int8']
#quantize = ['float32']
#optimize = ['cmsis-nn']
optimize = ['']
compress = [1]
limit = 20

[dataset]
kind = "UCI_HAR"
params.variant = "raw"
params.path = "data/UCI HAR Dataset/"

[[preprocessing]]
kind = "DatamodelConverter"

[[preprocessing]]
kind = "Class2BinMatrix"

[[preprocessing]]
kind = "Normalize"
params.method = 'z-score'
params.axis = 0
params.debug = true

[[data_augmentation]]
kind = "Mixup"

[[postprocessing]]
kind = "QuantizationAwareTraining"
export = true
params.width = 8
params.epochs = 0
params.batch_size = 64
params.model.params.fused_relu          = true

[model_template]
kind = "ResNet"
epochs = 0
batch_size = 64
params.prepool 		= 1
params.strides		= [1, 2]
params.num_blocks	= [2]
train = false
load = true

[model_template.optimizer]
kind = "SGD"
params.lr               = 0.05
params.momentum		= 0.9
params.weight_decay	= 5e-4

[model_template.optimizer.scheduler]
kind = "MultiStepLR"
params.milestones	= [100, 200, 250]
params.gamma		= 0.13

[[model]]
name = "uci-har_resnetv1_16"
params.filters          = [16, 16]
params.kernel_sizes     = [3, 3]
params.paddings         = [1, 1]
params.batch_norm       = false
disabled = false
#disabled = true

[[model]]
name = "uci-har_resnetv1_24"
params.filters          = [24, 24]
params.kernel_sizes     = [3, 3]
params.paddings         = [1, 1]
params.batch_norm       = false
disabled = false
#disabled = true

[[model]]
name = "uci-har_resnetv1_32"
params.filters          = [32, 32]
params.kernel_sizes     = [3, 3]
params.paddings         = [1, 1]
params.batch_norm       = false
disabled = false
#disabled = true

[[model]]
name = "uci-har_resnetv1_40"
params.filters          = [40, 40]
params.kernel_sizes     = [3, 3]
params.paddings         = [1, 1]
params.batch_norm       = false
disabled = false
#disabled = true

[[model]]
name = "uci-har_resnetv1_48"
params.filters          = [48, 48]
params.kernel_sizes     = [3, 3]
params.paddings         = [1, 1]
params.batch_norm       = false
disabled = false
#disabled = true

[[model]]
name = "uci-har_resnetv1_64"
params.filters          = [64, 64]
params.kernel_sizes     = [3, 3]
params.paddings         = [1, 1]
params.batch_norm       = false
disabled = false
#disabled = true

[[model]]
name = "uci-har_resnetv1_80"
params.filters          = [80, 80]
params.kernel_sizes     = [3, 3]
params.paddings         = [1, 1]
params.batch_norm       = false
disabled = false
#disabled = true
