[bench]
name = "GSC_ResNetv1-14_MFCCDolphin_int16_evaluate"
seed = 2
first_run = 1
last_run = 15

[learningframework]
kind = 'PyTorch'

[deploy]
target = 'Linux'
converter.kind = 'QualiaCodeGen'
quantize = ['int16']
optimize = ['']
compress = [1]

[dataset]
kind = "GSC"
params.variant = "v2"
params.path = "data/speech_commands_v0.02/"
params.subset = "no_background_noise"

[[preprocessing]]
kind = "Class2BinMatrix"

[[preprocessing]]
kind = "Normalize"
params.method = 'z-score'
params.axis = 0
params.debug = true

[[data_augmentation]]
kind = "GaussianNoise"
params.sigma = 0.00175

[[data_augmentation]]
kind = "TimeWarping"
params.sigma = 0.0675

[[data_augmentation]]
kind = "TimeShifting"
params.alpha = 1.0

#[[data_augmentation]]
#kind = "Mixup"
#params.alpha = 0.5

[[data_augmentation]]
kind = "MFCC"
params.evaluate = true
params.sample_rate = 16000
#params.n_mfcc = 64
params.n_mfcc = 10
params.log_mels = true
params.melkwargs.n_fft = 1024
params.melkwargs.n_mels = 40
#params.melkwargs.win_length = 1024
params.melkwargs.win_length = 640
#params.melkwargs.hop_length = 128
params.melkwargs.hop_length = 320
params.melkwargs.f_min = 20
params.melkwargs.f_max = 4000

# pad by hop_length to obtain expected 1 + floor( (n_samples - window_length) / hop_length) = 49 samples
# https://github.com/librosa/librosa/issues/595#issuecomment-313116650
params.melkwargs.pad = 320
params.melkwargs.center = false

#[[postprocessing]]
#kind = "FuseBatchNorm"
#export = true

[[postprocessing]]
kind = "QuantizationAwareTraining"
export = true
params.width = 16
params.epochs = 0
params.batch_size = 1536
params.force_q = 9

[model_template]
kind = "ResNet"
epochs = 0
load = true
train = false
batch_size = 1536
#params.input_shape	= [126, 64]
params.input_shape	= [49, 10]
params.prepool 		= 1
params.postpool   = 'avg'
params.kernel_sizes 	= [7, 3, 3]
params.paddings		= [3, 1, 1]
params.strides		= [1, 2]
params.batch_norm 	= false
params.bn_momentum	= 0.1
params.num_blocks	= [2]
params.dims		= 1

#[model_template.optimizer]
#kind = "Adam"
#params.lr               = 0.01
#params.momentum		= 0.9
#params.weight_decay	= 5e-4

#[model_template.optimizer.scheduler]
#kind = "MultiStepLR"
#params.milestones	= [25, 55, 80, 95, 110, 115]
#params.gamma		= 0.25



[[model]]
name = "gscdolphin_resnetv1-14_8"
params.filters 		= [8, 8, 8, 8]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_12"
params.filters 		= [12, 12, 12, 12]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_16"
params.filters 		= [16, 16, 16, 16]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_20"
params.filters 		= [20, 20, 20, 20]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_24"
params.filters 		= [24, 24, 24, 24]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_32"
params.filters 		= [32, 32, 32, 32]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_48"
params.filters 		= [48, 48, 48, 48]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_64"
params.filters 		= [64, 64, 64, 64]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_80"
params.filters 		= [80, 80, 80, 80]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
disabled = false
#disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_128"
params.filters 		= [128, 128, 128, 128]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
#disabled = false
disabled = true

[[model]]
name = "gscdolphin_resnetv1-14_192"
params.filters 		= [192, 192, 192, 192]
params.kernel_sizes	= [7, 3, 3, 3]
params.paddings		= [1, 1, 1, 1]
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
#disabled = false
disabled = true
