[bench]
name = "Ellcie-HAR_16-02-22_8acts_ResNetv1_float32_train"
seed = 5
first_run = 1
last_run = 1

[learningframework]
kind = 'PyTorch'

[deploy]
target = 'Linux'
converter.kind = 'QualiaCodeGen'
quantize = ['float32']
optimize = ['']

[dataset]
kind = "EllcieHAR"
params.variant = "UCA-EHAR"
params.path = "data/UCA-EHAR_16-02-22"

#[experimenttracking]
#kind = "Neptune"
#params.config = 'conf/neptune.toml'
#params.project_name = 'Qualia-EllcieHAR'

[[preprocessing]]
kind = "RemoveActivity"
params.activities = [
	#"STANDING",
	"STAND_TO_SIT",
	#"SITTING",
	"SIT_TO_STAND",
	#"WALKING",
	#"LYING",
	#"WALKING_DOWNSTAIRS",
	#"WALKING_UPSTAIRS",
	"DRIVING",
	##"NODDING",
	##"TRANSITION",
	#"RUNNING",
	#"DRINKING",
	"SIT_TO_LIE",
	"LIE_TO_SIT"
]

[[preprocessing]]
kind = "RemoveSensor"
params.sensorkinds = ["Barometer"]

#[[preprocessing]]
#kind = "BandPassFilter"
#params.f1 = 0.01
#params.f2 = 1.0
##params.f2 = 100.0
#params.sensorkind = "Barometer"
#params.dimension = "p"

[[preprocessing]]
kind = "DatasetSplitterBySubjects"
#['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = []

# test subjects with drinking
#Result(combination=array(['T4', 'T5', 'T7', 'T19', 'T20'], dtype='<U3'), mean=24.50350249729214, std=1.4015159401704411, ratios=array([23.186762536873157, 26.93521146293022, 25.361542018749738,
#       23.375860439574474, 24.051639583278106, 23.106022896963662,
#       23.70202569105265, 26.308955348915138], dtype=object))
#params.source_subjects = ['T1', 'T2', 'T3', 'T6', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T21']
#params.dest_subjects = ['T4', 'T5', 'T7', 'T19', 'T20']

#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T15', 'T16', 'T17', 'T18', 'T19', 'T20']#, 'T21']
#params.dest_subjects = ['T21']
#params.dest_subjects = ['T3']

params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T21']
params.dest_subjects = ['T5', 'T15', 'T17', 'T18', 'T19', 'T20']

#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T21']
#params.dest_subjects = ['T5', 'T15', 'T17', 'T18', 'T19', 'T20']


#params.source_subjects = ['T1', 'T2', 'T5', 'T6', 'T7', 'T8', 'T9', 'T12', 'T13', 'T16', 'T17', 'T19', 'T20', 'T21'] # 'T15'
#params.dest_subjects = ['T3', 'T4', 'T10', 'T14', 'T18']

#params.source_subjects = ['T3', 'T4', 'T5', 'T6']
#params.dest_subjects = ['T1', 'T2']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T12', 'T17', 'T18']
#params.dest_subjects = ['T19', 'T20', 'T21']

#params.source_subjects = ['T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T1', 'T2', 'T3', 'T4']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T5', 'T6', 'T7', 'T8']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T14', 'T16', 'T17', 'T18', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T9', 'T10', 'T12', 'T13']
#params.source_subjects = ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T19', 'T20', 'T21']
#params.dest_subjects = ['T14', 'T16', 'T17', 'T18']
#params.source_subjects = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T12', 'T13', 'T14', 'T16', 'T17', 'T18']
#params.dest_subjects = ['T19', 'T20', 'T21', 'T1']
params.source = "train"
params.dest = "test"

[[preprocessing]]
kind = "PrintHARDataModelSummary"

[[preprocessing]]
kind = "DatamodelConverter"

[[preprocessing]] # Must be applied before Class2BinMatrix and DatasetSplitter
kind = "Window"
#params.size = 32
#params.stride = 8
params.size = 64
params.stride = 16
params.unique_label_per_window = true
params.no_overlapping_labels = false

[[preprocessing]] # Must be applied after Window
kind = "Class2BinMatrix"
params.classes = 8 # PACK-2 12 classes, T1 15 classes, PACK-2+3 13 classes # 8 with STANDING

#[[preprocessing]]
#kind = "Normalize"
#params.method = 'z-score'
#params.axis = 0
#params.debug = true

#[[data_augmentation]]
#kind = "TimeShifting"

[[data_augmentation]]
kind = "TimeWarping"
params.sigma = 0.05

[[data_augmentation]]
kind = "Rotation"
params.sigma = 0.05

[[data_augmentation]]
kind = "GaussianNoise"
params.sigma = 0.175

[[data_augmentation]]
kind = "Mixup"

#[[postprocessing]]
#kind = "Torch2Keras"
#params.mapping = 'conf/torch2keras/resnetv1-6.toml'

#[[postprocessing]]
#kind = "RemoveKerasSoftmax"
#export = true

[[postprocessing]]
kind = "FuseBatchNorm"
export = true

[model_template]
kind = "ResNet"
#epochs = 195 # 0.717
#epochs = 250
#batch_size = 128 # 0.717
epochs = 350
batch_size = 768
params.prepool 		= 1
params.strides		= [1, 2]
params.num_blocks	= [2]
#load = true
#train = false

[model_template.optimizer]
#kind = "Adam"
#kind = "SGD"
#params.lr               = 0.01 # 0.717
#params.lr               = 0.01 # 0.717
#params.momentum		= 0.9
#kind = "SGD"
#params.lr               = 0.025 # 0.717
#params.momentum		= 0.9
#params.weight_decay	= 5e-4
kind = "RAdam"
params.lr = 0.005
params.weight_decay = 5e-4

[model_template.optimizer.scheduler]
kind = "MultiStepLR"
#params.milestones	= [100, 150, 175, 188] # 0.717
#params.milestones	= [75, 150, 200, 225]
#params.gamma		= 0.1 # 0.717
#params.milestones	= [75, 150, 200, 225]
params.milestones       = [100, 200, 250, 300, 325, 335]
params.gamma		= 0.1

[[model]]
name = "ellciehar_resnetv1_8"
params.filters 		= [8, 8]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = true

[[model]]
name = "ellciehar_resnetv1_16"
params.filters 		= [16, 16]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = true

[[model]]
name = "ellciehar_resnetv1_22-8+4"
params.strides		= [1, 2, 2, 2, 2]
params.num_blocks	= [2, 2, 2, 2]
params.filters 		= [12, 16, 20, 24, 32]
params.kernel_sizes 	= [7, 3, 3, 3, 3, 3]
params.paddings		= [3, 1, 1, 1, 1, 1]
params.batch_norm 	= true
params.bn_momentum	= 0.1
disabled = true

[[model]]
name = "ellciehar_resnetv1_14-8x2x2x2"
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
params.filters 		= [8, 16, 32, 64]
params.kernel_sizes 	= [7, 3, 3, 3, 3]
params.paddings		= [3, 1, 1, 1, 1]
params.batch_norm 	= true
params.bn_momentum	= 0.1
disabled = true

[[model]]
name = "ellciehar_resnetv1_14-16"
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
params.filters 		= [6, 12, 24, 48]
params.kernel_sizes 	= [7, 3, 3, 3, 3]
params.paddings		= [3, 1, 1, 1, 1]
params.batch_norm 	= true
params.bn_momentum	= 0.1
disabled = false

[[model]]
name = "ellciehar_resnetv1_24"
params.filters 		= [24, 24]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = true

[[model]]
name = "ellciehar_resnetv1_32"
params.filters 		= [32, 32]
params.kernel_sizes 	= [7, 3, 3]
params.paddings		= [1, 1, 1]
params.batch_norm 	= true
params.bn_momentum	= 0.1
disabled = true

[[model]]
name = "ellciehar_resnetv1_40"
params.filters 		= [40, 40]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= true
params.bn_momentum	= 0.1
disabled = true

[[model]]
name = "ellciehar_resnetv1_48"
params.filters 		= [48, 48]
params.kernel_sizes 	= [7, 3, 3]
params.paddings		= [3, 1, 1]
params.batch_norm 	= true
params.bn_momentum	= 0.1
disabled = true

[[model]]
name = "ellciehar_resnetv1_14-48"
params.strides		= [1, 2, 2, 2]
params.num_blocks	= [2, 2, 2]
params.filters 		= [48, 48, 48, 48]
params.kernel_sizes 	= [7, 3, 3, 3, 3]
params.paddings		= [3, 1, 1, 1, 1]
params.batch_norm 	= true
params.bn_momentum	= 0.1
disabled = true

[[model]]
name = "ellciehar_resnetv1_64"
params.filters 		= [64, 64]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = true

[[model]]
name = "ellciehar_resnetv1_80"
params.filters 		= [80, 80]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.batch_norm 	= false
disabled = true

[[model]]
name = "ellciehar_resnetv1_96-128"
params.filters 		= [96, 96, 192]
params.kernel_sizes 	= [3, 3]
params.paddings		= [1, 1]
params.strides		= [1, 2, 2]
params.num_blocks	= [2, 2]
params.batch_norm 	= true
disabled = true
